# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 7 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: nikiforovall
google_analytics: UA-164555539-1
title: n+1 IT blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: nikiforovall.blog

description: Blog
author:
  name: Alexey Nikiforov
  email: nikiforovalekcey@gmail.com
  github: nikiforovAll
  twitter: nikiforovall
  linkedin: alexey-nikiforov-430259111
  bio: Jibber-jabbering about programming and IT.
  email_md5: e86fa0938976c38907a302ecb208f011

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://secure.gravatar.com/avatar/e86fa0938976c38907a302ecb208f011

BASE_PATH: https://thearthouse.github.io/blew/

plugins:
  - jekyll-paginate



# Site structure
about_page_path: "about.html"
